"""Tests for catalog/hooks/attribution-guard.{sh,ps1} (v4.13.1 Phase 6).

The hook is a thin adapter over `scripts/nexus_git_attribution.py scan`. It must
block AI attribution in trailer or footer position on every publishing route,
let a sentence that names a tool as its subject pass, pass the text that
DESCRIBES the patterns (this plan's own CHANGELOG and pull request wording), and
warn rather than block when a body cannot be read safely.

Every test runs against BOTH implementations via the `run` fixture, so the
suite is also the .sh/.ps1 parity check.

Run from the repo root:
    python -m pytest catalog/hooks/tests/test_attribution_guard.py -v
"""
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

import pytest

_HOOKS_DIR = Path(__file__).resolve().parent.parent
_HOOK_SH = _HOOKS_DIR / "attribution-guard.sh"
_HOOK_PS1 = _HOOKS_DIR / "attribution-guard.ps1"
_ROBOT = "\U0001F916"
_AGENT_TRAILER = "Co-Authored-By: Claude <noreply@anthropic.com>"


@pytest.fixture(params=["sh", "ps1"])
def run(request, tmp_path: Path):
    if request.param == "sh":
        prefix = [request.getfixturevalue("bash_bin"), str(_HOOK_SH)]
    else:
        prefix = [request.getfixturevalue("powershell_bin"), "-NoProfile", "-File", str(_HOOK_PS1)]
    work = tmp_path / "work"
    work.mkdir()

    def _run(payload: dict | str, extra: dict[str, str] | None = None, cwd: Path | None = None
             ) -> subprocess.CompletedProcess:
        body = payload if isinstance(payload, str) else json.dumps(payload)
        env = {**os.environ}
        for key in ("NEXUS_DISABLED_HOOKS", "NEXUS_HOOK_PROFILE", "NEXUS_ATTRIBUTION_SCRIPT"):
            env.pop(key, None)
        env.update(extra or {})
        return subprocess.run(prefix, input=body.encode("utf-8"), capture_output=True,
                              cwd=str(cwd or work), env=env, timeout=180, check=False)

    _run.work = work  # type: ignore[attr-defined]
    return _run


def _bash(command: str, cwd: Path | None = None) -> dict:
    payload = {"hook_event_name": "PreToolUse", "tool_name": "Bash", "tool_input": {"command": command}}
    if cwd is not None:
        payload["cwd"] = str(cwd)
    return payload


def _err(result: subprocess.CompletedProcess) -> str:
    return result.stderr.decode("utf-8", "replace")


# --- blocked routes -----------------------------------------------------------------

@pytest.mark.parametrize("command", [
    f'git commit -m "x" -m "{_AGENT_TRAILER}"',
    'gh pr create --title t --body "Generated with Claude Code"',
    f"git commit -F - <<'EOF'\nfeat: x\n\nbody\n\n{_AGENT_TRAILER}\nEOF\n",
    f"git commit -m \"$(cat <<'EOF'\nfeat: x\n\n{_AGENT_TRAILER}\nEOF\n)\"",
    'git tag -a v1 -m "Release\n\nMade with Cursor"',
    'gh issue comment 4 --body "Fixed.\n\nCo-authored-by: Codex <noreply@openai.com>"',
    'gh release create v1 --notes "Notes\n\n' + _ROBOT + ' Generated with Claude Code"',
    'gh api repos/o/r/issues/1/comments -f body="Done\n\nGenerated by Copilot"',
    'gh pr edit 3 --body ":robot: badge"',
])
def test_attribution_is_blocked_on_every_inline_route(run, command):
    result = run(_bash(command))
    assert result.returncode == 2, _err(result)
    assert "[attribution-guard] BLOCKED" in _err(result)
    assert "pattern" in _err(result)


@pytest.mark.parametrize("command", [
    'gh pr create --title t --body "Summary\n\n_Generated with Claude Code_"',
    'gh pr create --title t --body "Summary\n\nGenerated with **Claude Code**"',
    'gh pr create --title t --body "Summary\n\n<sub>Generated with Claude Code</sub>"',
    f'GIT_AUTHOR_DATE=now git commit -m "x" -m "{_AGENT_TRAILER}"',
    f'env git commit -m "x" -m "{_AGENT_TRAILER}"',
    f'git --no-pager -c color.ui=never commit -m "x" -m "{_AGENT_TRAILER}"',
    f'git commit -m "x" --trailer "{_AGENT_TRAILER}"',
    f'git merge feat -m "Merge\n\n{_AGENT_TRAILER}"',
    f"git commit -F - <<'MSG-END'\nfeat: x\n\n{_AGENT_TRAILER}\nMSG-END\n",
    'git commit -m "x" -m "Co-authored-by: Claude Opus 5.5 <opus@example.com>"',
    'git commit -m "x" -m "Co-authored-by: ChatGPT 5 <me@example.com>"',
    'gh pr create --title t --body "Summary\n\nGenerated with Claude Opus 5.5"',
    'gh pr create --title t --body "Summary\n\nGenerated with Claude Code - https://claude.com/claude-code"',
    'gh pr create --title t --body "Summary\n\nGenerated with [Claude Code][1]"',
    'gh pr create --title t --body "Summary\n\nGenerated with Claude Code, reviewed by me"',
    'git commit -m "x" --trailer "Co-authored-by=Claude <noreply@anthropic.com>"',
    f'command git commit -m "x" -m "{_AGENT_TRAILER}"',
    'gh pr create --title t --body "Summary\n\nGenerated with Claude Code by Anthropic"',
])
def test_deep_pass_attribution_routes_are_blocked(run, command):
    """Routes and footer forms the Phase 9 adversarial pass found passing."""
    result = run(_bash(command))
    assert result.returncode == 2, _err(result)


def test_backslash_body_file_and_gh_api_input_are_read(run):
    body = run.work / "body.md"
    body.write_text(f"Summary\n\n{_AGENT_TRAILER}\n", encoding="utf-8")
    windows_path = str(body).replace("/", "\\")
    assert run(_bash(f"gh pr create --title t --body-file {windows_path}", run.work)).returncode == 2
    assert run(_bash("gh api repos/o/r/pulls --input body.md", run.work)).returncode == 2


def test_body_file_route_is_blocked(run):
    (run.work / "body.md").write_text(f"Summary\n\n{_AGENT_TRAILER}\n", encoding="utf-8")
    assert run(_bash("gh pr create --title t --body-file body.md", run.work)).returncode == 2
    assert run(_bash("git commit -F body.md", run.work)).returncode == 2


def test_fill_reads_the_commit_range(run, tmp_path):
    repo = run.work
    # The range must already hold an attributed commit (for example one pulled from someone
    # else), so this throwaway repository's commits bypass the machine's Git attribution hooks.
    no_hooks = tmp_path / "no-hooks"
    no_hooks.mkdir()
    git = ["git", "-C", str(repo), "-c", "user.name=Test User", "-c", "user.email=test@example.com",
           "-c", f"core.hooksPath={no_hooks}"]
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True)
    subprocess.run([*git, "commit", "-q", "--allow-empty", "-m", "base"], check=True)
    subprocess.run([*git, "switch", "-q", "-c", "feat"], check=True)
    subprocess.run([*git, "commit", "-q", "--allow-empty", "-m", f"feat: x\n\n{_AGENT_TRAILER}"], check=True)
    assert run(_bash("gh pr create --fill --base main", repo)).returncode == 2


@pytest.mark.parametrize("tool", ["mcp__github__create_pull_request", "mcp__plugin_github_github__add_issue_comment"])
def test_github_mcp_tools_are_blocked(run, tool):
    payload = {"hook_event_name": "PreToolUse", "tool_name": tool,
               "tool_input": {"title": "x", "body": f"Summary\n\n{_AGENT_TRAILER}"}}
    assert run(payload).returncode == 2


# --- passing text -------------------------------------------------------------------

@pytest.mark.parametrize("command", [
    'gh pr create --title t --body "Output generated with pandoc"',
    'git commit -m "Pair work" -m "Co-authored-by: Jane Doe <jane@example.com>"',
    'git commit -m "docs: mention claude-code-templates repository"',
    'git commit -m "feat: route Claude Code sessions through the new hook"',
    'git commit -m "Pair work" -m "Co-authored-by: Kimi Lee <kimi.lee@example.com>"',
    'git commit -m "Pair work" -m "Co-authored-by: Jane Roe <jane@bot.io>"',
    'git commit -m "Tooling" -m "Made-with: VS Code"',
    'gh pr create --title t --body "Notes\n\nGenerated with Claude Code footers are now rejected by the hook."',
    'gh pr create --title t --body "Notes\n\nGenerated with Claude Code: see the docs for how the hook rejects this footer."',
    "git status",
    "gh pr list",
])
def test_subject_mentions_and_unrelated_commands_pass(run, command):
    result = run(_bash(command))
    assert result.returncode == 0, _err(result)
    assert "BLOCKED" not in _err(result)


_DESCRIPTIVE_TEXT = [
    ("- `attribution-guard` hook: blocks agent `Co-Authored-By:` trailers, line-start "
    "\"Generated with <agent>\" footers, and robot-emoji badges on git commit, git tag, gh, "
    "gh api, and GitHub MCP publishing routes; a sentence that names a tool as its subject passes."),
    ("## Summary\n\nAdds two guard hooks. The attribution guard blocks a `Co-Authored-By:` "
    "trailer naming an agent and a \"Generated with Claude Code\" footer, and passes "
    "`gh pr create --body \"Output generated with pandoc\"`.\n\n## How to test\n\n"
    "Run `python -m pytest catalog/hooks/tests/test_attribution_guard.py -q`."),
]


@pytest.mark.parametrize("text", _DESCRIPTIVE_TEXT)
def test_text_that_describes_the_patterns_passes(run, text):
    (run.work / "body.md").write_text(text, encoding="utf-8")
    assert run(_bash("gh pr create --title t --body-file body.md", run.work)).returncode == 0
    payload = {"hook_event_name": "PreToolUse", "tool_name": "Write",
               "tool_input": {"file_path": "CHANGELOG.md", "content": text}}
    result = run(payload)
    assert result.returncode == 0 and "WARNING" not in _err(result)


def test_changelog_write_with_attribution_warns_but_passes(run):
    payload = {"hook_event_name": "PreToolUse", "tool_name": "Write",
               "tool_input": {"file_path": "docs/notes.md", "content": f"Notes\n\n{_AGENT_TRAILER}\n"}}
    result = run(payload)
    assert result.returncode == 0
    assert "[attribution-guard] WARNING" in _err(result)


# --- cannot verify ------------------------------------------------------------------

@pytest.mark.parametrize("route", [
    "gh pr create --title t --body-file missing.md",
    "gh pr create --title t --body-file \"$BODY\"",
    "gh pr create --title t --body-file -",
    "gh pr create --title t --body-file big.md",
])
def test_unreadable_body_warns_and_passes(run, route):
    (run.work / "big.md").write_text("x" * (1024 * 1024 + 1), encoding="utf-8")
    result = run(_bash(route, run.work))
    assert result.returncode == 0
    assert "cannot verify body" in _err(result)


@pytest.mark.parametrize("body", ["", "not json", "[1]", "{}"])
def test_malformed_or_absent_input_exits_zero(run, body):
    assert run(body).returncode == 0


def test_failing_helper_warns_and_passes(run, tmp_path):
    helper = tmp_path / "broken_helper.py"
    helper.write_text("import sys; sys.exit(1)\n", encoding="utf-8")
    result = run(_bash(f'git commit -m "x" -m "{_AGENT_TRAILER}"'), {"NEXUS_ATTRIBUTION_SCRIPT": str(helper)})
    assert result.returncode == 0
    assert "cannot verify body (nexus_git_attribution.py failed)" in _err(result)


def test_long_matched_text_is_truncated_and_control_stripped(run):
    # A footer must end at the agent name, so the long offending line is a trailer instead.
    line = _AGENT_TRAILER + " " + "\x1b[31m" + "A" * 300
    result = run(_bash(f'gh pr create --title t --body "Summary\n\n{line}"'))
    assert result.returncode == 2
    reported = next(ln for ln in _err(result).splitlines() if ln.startswith("Line: "))
    assert len(reported) <= len("Line: ") + 80
    assert "\x1b" not in reported


def test_user_escape_disables_it_but_minimal_profile_does_not(run):
    payload = _bash(f'git commit -m "x" -m "{_AGENT_TRAILER}"')
    assert run(payload, {"NEXUS_DISABLED_HOOKS": "attribution-guard"}).returncode == 0
    assert run(payload, {"NEXUS_HOOK_PROFILE": "minimal"}).returncode == 2
