"""Codex-native agent and hook materialization (v3.15.8 Phase 5).

Codex reads two surfaces that no other Nexus-Hub platform reads in the same
shape, and neither is a verbatim copy of the catalog:

  - **Custom agents** are standalone TOML files under ``~/.codex/agents/`` and
    ``<project>/.codex/agents/``. Every file must define ``name``,
    ``description``, and ``developer_instructions``; ``model``,
    ``model_reasoning_effort``, ``sandbox_mode``, ``mcp_servers``, and
    ``skills.config`` are optional. The catalog ships Markdown agents with
    ``name`` / ``description`` / ``tools`` frontmatter, so this module transforms
    rather than copies.
  - **Hooks** are registered in ``hooks.json`` next to an active config layer
    (``~/.codex/hooks.json``, ``<project>/.codex/hooks.json``). Codex's event
    names line up with the ones Nexus-Hub already uses in
    ``catalog/hooks/settings.json``, but its ``matcher`` vocabulary does not:
    only ``Bash``, ``apply_patch`` (aliases ``Edit`` / ``Write``), MCP tool
    names, and other local function tools are recognized. Matchers with no
    Codex equivalent are dropped rather than guessed at.

Two Codex behaviors shape the design.

``hooks.json`` is a shared file: a user may already have their own hooks in it,
and Codex loads every hook source additively. So this module performs a
structured merge keyed on ownership rather than writing the file wholesale.
A handler is Nexus-Hub-owned when its command references the hooks directory
this integration installs into; nothing else is touched, and teardown removes
only owned handlers.

Each handler may carry ``commandWindows``, an official Windows-only command
override. That maps exactly onto Nexus-Hub's ``.sh`` / ``.ps1`` sibling
convention: the POSIX command goes in ``command`` and the PowerShell sibling in
``commandWindows``, so a Windows user gets the same guardrail from the same
registration instead of a silently absent one.

This module is stdlib-only and makes no outbound calls.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from ._catalog_adapters import _split_frontmatter
from ._hooks_common import script_basename, sourced_modules, strip_owned_handlers
from ._owned import write_owned_file
from .base import IntegrationBase
from .result import FileAction

# Codex hook events, per the official hooks reference. Nexus-Hub only emits the
# subset that catalog/hooks/settings.json actually registers; the rest are listed
# so a future settings.json event is validated rather than silently dropped.
CODEX_HOOK_EVENTS = frozenset(
    {
        "SessionStart",
        "SessionEnd",
        "PreToolUse",
        "PermissionRequest",
        "PostToolUse",
        "PreCompact",
        "PostCompact",
        "UserPromptSubmit",
        "SubagentStart",
        "SubagentStop",
        "Stop",
    }
)

# Codex ignores any configured matcher for these events, so emitting one would
# be noise that implies filtering Codex does not perform.
CODEX_MATCHERLESS_EVENTS = frozenset({"UserPromptSubmit", "Stop"})

# Claude-style event names Codex implements under a DIFFERENT name. Without an
# alias the chain is dropped for want of a same-named event, which is how
# Nexus-Hub's Notification chain (the "agent is blocked on the human" trigger)
# silently failed to reach Codex.
#
# Verified 2026-08-04 against the Codex implementation itself rather than prose
# docs, because openai/codex ships no docs/hooks.md: `codex-rs/hooks/src/events/`
# contains a dedicated `permission_request.rs` module, and the serde wire names in
# `codex-rs/hooks/src/lib.rs` enumerate PermissionRequest alongside Stop. That
# makes Codex the only platform besides Claude Code able to express the
# attention-required trigger.
CODEX_EVENT_ALIASES = {"Notification": "PermissionRequest"}


# Tool-name matcher tokens Codex recognizes for PreToolUse / PostToolUse.
# `apply_patch` is the canonical name for file edits; `Edit` and `Write` are its
# documented aliases. Nexus-Hub's `PowerShell`, `MultiEdit`, and `Skill` tokens
# have no Codex equivalent -- Codex routes every shell call through `Bash` -- so
# they are dropped instead of being mapped onto an approximation.
CODEX_TOOL_MATCHERS = frozenset({"Bash", "apply_patch", "Edit", "Write"})

# Tools that cannot mutate the workspace. An agent whose catalog `tools` list is
# entirely within this set is emitted with `sandbox_mode = "read-only"`, which
# constrains the agent rather than widening it: the inference can only ever fail
# closed. Any unrecognized tool leaves sandbox_mode unset so the agent inherits
# the parent session.
_READ_ONLY_TOOLS = frozenset(
    {"read", "glob", "grep", "ls", "webfetch", "websearch", "notebookread"}
)

_GENERATED_HEADER = (
    "# Generated by Nexus-Hub from {source}. Do not edit by hand.\n"
    "# Re-run the installer to refresh; local edits are replaced on upgrade.\n"
)


# ----- TOML emission ------------------------------------------------------


def _toml_basic_string(value: str) -> str:
    """Return ``value`` as a single-line TOML basic string."""
    collapsed = " ".join(value.split())
    escaped = collapsed.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")
    return f'"{escaped}"'


def _toml_multiline_string(value: str) -> str:
    """Return ``value`` as a TOML multi-line string.

    Prefers a literal (``'''``) string so the agent body stays readable in the
    generated file, since literals need no escaping at all. Falls back to a
    basic (``\"\"\"``) string with full escaping when the body contains ``'''``
    or ends in a quote, which a literal cannot represent.
    """
    text = value.replace("\r\n", "\n").replace("\r", "\n").strip("\n")
    if "'''" not in text and not text.endswith("'"):
        return f"'''\n{text}\n'''"
    escaped = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if escaped.endswith('"'):
        escaped = escaped[:-1] + '\\"'
    return f'"""\n{escaped}\n"""'


def infer_sandbox_mode(tools_field: str) -> str | None:
    """Return ``"read-only"`` when every listed catalog tool is non-mutating.

    Codex has no equivalent of the catalog's ``tools`` allowlist, so the field
    cannot be carried across verbatim. Rather than drop the intent entirely, an
    agent that the catalog already restricts to read-only tools is sandboxed
    read-only in Codex. An empty list, or any tool outside the known read-only
    set, yields ``None`` (inherit from the parent session).
    """
    tools = [item.strip() for item in tools_field.split(",") if item.strip()]
    if not tools:
        return None
    if all(tool.lower() in _READ_ONLY_TOOLS for tool in tools):
        return "read-only"
    return None


def render_agent_toml(source_name: str, markdown: str) -> bytes | None:
    """Transform one ``catalog/agents/<name>.md`` into a Codex agent TOML file.

    Returns ``None`` when the source lacks the fields Codex requires, so the
    caller can skip it rather than emit a file Codex will reject at load time.
    """
    meta, body = _split_frontmatter(markdown)
    name = meta.get("name", "").strip() or source_name
    description = meta.get("description", "").strip()
    instructions = body.strip()
    if not description or not instructions:
        return None

    lines = [_GENERATED_HEADER.format(source=f"catalog/agents/{source_name}.md")]
    tools = meta.get("tools", "").strip()
    if tools:
        lines.append(f"# Catalog tools: {tools}\n")
    lines.append(f"name = {_toml_basic_string(name)}\n")
    lines.append(f"description = {_toml_basic_string(description)}\n")
    sandbox_mode = infer_sandbox_mode(tools)
    if sandbox_mode:
        lines.append(f"sandbox_mode = {_toml_basic_string(sandbox_mode)}\n")
    lines.append(f"developer_instructions = {_toml_multiline_string(instructions)}\n")
    return "".join(lines).encode("utf-8")


# ----- ownership-aware writes ---------------------------------------------


# `write_owned_file` moved to `_owned` in Phase 7, when Kimi needed the same
# manifest-aware write. Re-exported here so this module's public surface (and the
# Phase 5 tests that import it) is unchanged.


def agents_to_codex_toml(
    ctx, key: str, src_agents_dir: Path, dst_agents_dir: Path
) -> list[FileAction]:
    """Materialize ``catalog/agents/*.md`` as Codex custom-agent TOML files."""
    if not src_agents_dir.exists():
        ctx.manifest.log(key, f"missing-tree: {src_agents_dir}")
        return [FileAction(path=str(src_agents_dir), action="not-found")]
    IntegrationBase._ensure_dir(dst_agents_dir, ctx)
    actions: list[FileAction] = []
    for md in sorted(src_agents_dir.glob("*.md")):
        content = render_agent_toml(md.stem, md.read_text(encoding="utf-8"))
        if content is None:
            ctx.manifest.log(key, f"skip agent (missing required fields): {md.name}")
            continue
        actions.append(
            write_owned_file(ctx, key, dst_agents_dir / f"{md.stem}.toml", content)
        )
    return actions


# ----- hook registration --------------------------------------------------


def _normalize_matcher(event: str, matcher: str) -> str | None:
    """Map a Nexus-Hub matcher onto Codex's matcher vocabulary.

    Returns ``None`` when no alternative survives, meaning the group has no
    Codex equivalent and must be skipped. Returns ``""`` when the event takes no
    matcher (or the source matcher was already empty), meaning "match all".
    """
    if event in CODEX_MATCHERLESS_EVENTS:
        return ""
    matcher = matcher.strip()
    if not matcher:
        return ""
    supported = [
        part for part in matcher.split("|") if part.strip() in CODEX_TOOL_MATCHERS
    ]
    if not supported:
        return None
    return "|".join(supported)


def _split_command(command: str) -> tuple[str, str] | None:
    """Split a catalog hook command into (runner, script).

    Codex is the only adapter that needs the runner as well as the script, to
    preserve ``python3`` vs ``python`` for a ``.py`` hook, so it keeps this thin
    wrapper over the shared ``script_basename``.
    """
    parts = command.split()
    script = script_basename(command)
    if script is None:
        return None
    return parts[0], script


def build_hook_entries(
    settings: dict, src_hooks_dir: Path, command_base: str
) -> tuple[dict, set[str], list[str]]:
    """Build Codex hook groups from ``catalog/hooks/settings.json``.

    Returns ``(events, scripts, skipped)`` where ``events`` is the ``hooks``
    mapping to merge into ``hooks.json``, ``scripts`` is every catalog file that
    must be copied alongside it (including ``.ps1`` siblings), and ``skipped``
    describes each group dropped for want of a Codex equivalent.
    """
    events: dict[str, list] = {}
    scripts: set[str] = set()
    skipped: list[str] = []

    for event, groups in settings.get("hooks", {}).items():
        # Resolve a Claude-style name onto Codex's own name before the membership
        # test, or an aliased chain is dropped as "no Codex event of that name".
        event = CODEX_EVENT_ALIASES.get(event, event)
        if event not in CODEX_HOOK_EVENTS:
            skipped.append(f"{event}: no Codex event of that name")
            continue
        for group in groups:
            matcher = _normalize_matcher(event, group.get("matcher", ""))
            if matcher is None:
                skipped.append(
                    f"{event}/{group.get('matcher', '')}: no Codex matcher equivalent"
                )
                continue
            handlers: list[dict] = []
            for handler in group.get("hooks", []):
                split = _split_command(handler.get("command", ""))
                if split is None:
                    continue
                runner, script = split
                if not (src_hooks_dir / script).exists():
                    skipped.append(
                        f"{event}/{script}: script absent from catalog/hooks"
                    )
                    continue
                scripts.add(script)
                entry: dict[str, object] = {"type": "command"}
                if script.endswith(".py"):
                    entry["command"] = f"{runner} {command_base}/{script}"
                    entry["commandWindows"] = f"python {command_base}/{script}"
                else:
                    entry["command"] = f"bash {command_base}/{script}"
                    sibling = f"{Path(script).stem}.ps1"
                    if (src_hooks_dir / sibling).exists():
                        scripts.add(sibling)
                        entry["commandWindows"] = (
                            "powershell -NoProfile -ExecutionPolicy Bypass "
                            f"-File {command_base}/{sibling}"
                        )
                entry["statusMessage"] = f"Nexus-Hub {Path(script).stem}"
                handlers.append(entry)
            if not handlers:
                continue
            emitted: dict[str, object] = {}
            if matcher:
                emitted["matcher"] = matcher
            emitted["hooks"] = handlers
            events.setdefault(event, []).append(emitted)

    # Shared modules are not registered anywhere, so they must be resolved from
    # the delivered script bodies. Without this a hook that sources one is copied
    # and registered but exits silently on every run.
    scripts |= sourced_modules(scripts, src_hooks_dir)

    return events, scripts, skipped


def merge_hooks_json(
    ctx, key: str, dst: Path, owned_events: dict, owned_base: str
) -> FileAction:
    """Merge Nexus-Hub hook groups into ``hooks.json``, preserving user entries.

    A malformed existing file is never overwritten: Codex would lose the user's
    hooks, and the parse failure is more likely to be a transient local edit than
    something the installer should resolve. The file is kept and the reason
    logged. A successful merge writes atomically through a temp file, so a
    failure part-way leaves the original intact, and backs the previous content
    up next to the file before the first mutation.
    """
    existing: dict = {}
    if dst.exists():
        raw = dst.read_text(encoding="utf-8")
        try:
            parsed = json.loads(raw) if raw.strip() else {}
        except json.JSONDecodeError as exc:
            ctx.manifest.log(key, f"skip-malformed-json: {dst} ({exc})")
            return FileAction(path=str(dst), action="kept")
        if not isinstance(parsed, dict):
            ctx.manifest.log(key, f"skip-non-object-json: {dst}")
            return FileAction(path=str(dst), action="kept")
        existing = parsed

    merged = dict(existing)
    hooks = dict(merged.get("hooks") or {})
    for event in list(hooks):
        hooks[event] = strip_owned_handlers(list(hooks[event] or []), owned_base)
    for event, groups in owned_events.items():
        hooks[event] = list(hooks.get(event) or []) + list(groups)
    merged["hooks"] = {event: groups for event, groups in hooks.items() if groups}

    content = (json.dumps(merged, indent=2) + "\n").encode("utf-8")
    if dst.exists() and dst.read_bytes() == content:
        ctx.manifest.track(key, str(dst))
        return FileAction(path=str(dst), action="unchanged")

    existed = dst.exists()
    if not ctx.dry_run:
        dst.parent.mkdir(parents=True, exist_ok=True)
        if existed:
            backup = dst.with_suffix(dst.suffix + ".nexus-hub.bak")
            backup.write_bytes(dst.read_bytes())
            ctx.manifest.track(key, str(backup))
        tmp = dst.with_suffix(dst.suffix + ".nexus-hub.tmp")
        tmp.write_bytes(content)
        os.replace(tmp, dst)
    ctx.manifest.track(key, str(dst))
    return FileAction(path=str(dst), action="updated" if existed else "created")


def prune_hooks_json(dst: Path, owned_base: str, dry_run: bool) -> FileAction:
    """Remove Nexus-Hub handlers from ``hooks.json`` during teardown.

    The file is deleted only when nothing but our own entries remained; a file
    that still holds user hooks is rewritten without ours.
    """
    if not dst.exists():
        return FileAction(path=str(dst), action="not-found")
    try:
        parsed = json.loads(dst.read_text(encoding="utf-8") or "{}")
    except json.JSONDecodeError:
        return FileAction(path=str(dst), action="kept")
    if not isinstance(parsed, dict):
        return FileAction(path=str(dst), action="kept")

    hooks = dict(parsed.get("hooks") or {})
    for event in list(hooks):
        survivors = strip_owned_handlers(list(hooks[event] or []), owned_base)
        if survivors:
            hooks[event] = survivors
        else:
            del hooks[event]

    remainder = {k: v for k, v in parsed.items() if k != "hooks"}
    if not hooks and not remainder:
        if not dry_run:
            dst.unlink(missing_ok=True)
        return FileAction(path=str(dst), action="removed")

    remainder["hooks"] = hooks
    content = (json.dumps(remainder, indent=2) + "\n").encode("utf-8")
    if dst.read_bytes() == content:
        return FileAction(path=str(dst), action="unchanged")
    if not dry_run:
        dst.write_bytes(content)
    return FileAction(path=str(dst), action="updated")


__all__ = [
    "CODEX_HOOK_EVENTS",
    "CODEX_MATCHERLESS_EVENTS",
    "CODEX_TOOL_MATCHERS",
    "agents_to_codex_toml",
    "build_hook_entries",
    "infer_sandbox_mode",
    "merge_hooks_json",
    "prune_hooks_json",
    "render_agent_toml",
    "write_owned_file",
]
