"""Claude Code (Anthropic) integration."""

from __future__ import annotations

import json

from .base import InstallContext, MarkdownIntegration, SkillsIntegration
from .result import FileAction, WriteResult


_PROJECT_SETTINGS_STUB = {
    "_comment": (
        "Project-local Claude Code permissions. Generated by `nexus-hub init`. "
        "Edit freely; nexus-hub init never overwrites an existing settings.json."
    ),
    "permissions": {
        "allow": [
            "Read",
            "Glob",
            "Grep",
        ]
    },
}


class ClaudeIntegration(MarkdownIntegration, SkillsIntegration):
    key = "claude"
    display_name = "Claude Code (Anthropic)"
    instruction_mode = "shared"
    config = {
        "global_dir": "~/.claude",
        "workspace_dir": ".claude",
        # Workspace CLAUDE.md lands at the project root (where Claude Code reads
        # it), not under .claude/; skills/commands/agents/rules still mirror
        # under .claude/. Matches the legacy bash installer (DF-001).
        "instruction_workspace_dir": "",
        "instruction_file": "CLAUDE.md",
        "instruction_template": "templates/ai-instructions/base-claude.md",
        "skills_subdir": "skills",
        "commands_subdir": "commands",
        "agents_subdir": "agents",
        "rules_subdir": "rules",
        "hooks_subdir": "hooks",
        "hooks_supported": True,
        "permissions_file": "configs/permissions/claude-permissions.json",
    }

    def wire_project_surfaces(self, ctx: InstallContext) -> WriteResult:
        """Write a `.claude/settings.json` stub when none exists.

        `nexus-hub init` calls this to bootstrap a Claude project surface from
        a global install. The stub never overwrites an existing settings.json;
        it returns `kept` so the user's customizations survive.
        """
        result = WriteResult()
        claude_dir = (ctx.target_root / self.config["workspace_dir"]).resolve()
        if not ctx.dry_run:
            claude_dir.mkdir(parents=True, exist_ok=True)
        dst = claude_dir / "settings.json"
        if dst.exists():
            ctx.manifest.log(self.key, f"skip-existing: {dst}")
            result.files.append(FileAction(path=str(dst), action="kept"))
            return result
        body = json.dumps(_PROJECT_SETTINGS_STUB, indent=2) + "\n"
        if not ctx.dry_run:
            dst.write_text(body, encoding="utf-8")
        ctx.manifest.track(self.key, str(dst))
        result.files.append(FileAction(path=str(dst), action="created"))
        return result
