"""Claude Code (Anthropic) integration."""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

from .base import InstallContext, MarkdownIntegration, SkillsIntegration
from .result import FileAction, WriteResult


# Claude's install-time behavioral defaults are DECLARED in
# configs/platform-defaults.json and read here at runtime, so this module holds
# no second copy that can drift out of step with the shipped template. See
# configs/README.md for the schema and the do-not-invent rule.
#
# Candidate locations, in priority order. The installers deliberately do NOT
# copy configs/ into ~/.nexus-hub (they only read configs/permissions/ from a
# checkout), so an installed tree finds the file only when the one-line
# bootstrap materialized a full source tree under ~/.nexus-hub/src.
_DEFAULTS_CANDIDATES = (
    Path(__file__).resolve().parents[3] / "configs" / "platform-defaults.json",
    Path.home() / ".nexus-hub" / "src" / "configs" / "platform-defaults.json",
)

# Offline fallback for installed trees that carry no source checkout. Plain
# absence is the EXPECTED case there, so it degrades silently; only a file that
# exists but cannot be read is worth a note. These literals are kept honest by
# `python scripts/sync_platform_defaults.py --check`, which fails the build when
# they drift away from the declared values.
_FALLBACK_SETTINGS = {
    "effortLevel": "high",
    "model": "opus",
    "env": {
        "CLAUDE_CODE_EFFORT_LEVEL": "high",
    },
}

_STUB_COMMENT = (
    "Project-local Claude Code settings. Generated by `nexus-hub init` from "
    "configs/platform-defaults.json, the single source for per-platform install "
    "defaults. Edit freely; nexus-hub init never overwrites an existing "
    "settings.json. effortLevel sets the default reasoning effort (low / medium "
    "/ high / xhigh). model pins the default model. "
    "env.CLAUDE_CODE_EFFORT_LEVEL is the highest-precedence effort lever: it "
    "pins the effort past the VS Code effort toggle on every new session. "
    "Keep both effort keys aligned: set them to 'medium' for cheaper routine "
    "work or 'xhigh' for deeper reasoning. Remove model to use your account default."
)

_STUB_PERMISSIONS = {
    "allow": [
        "Read",
        "Glob",
        "Grep",
    ]
}


def _load_declared_settings(candidates=_DEFAULTS_CANDIDATES) -> dict:
    """Return Claude's declared install defaults, degrading to the fallback.

    `nexus-hub init` must never fail because a repo-internal source file is
    absent, so every read problem resolves to the built-in fallback. A file that
    is merely missing is the normal installed-tree case and stays silent; a file
    that exists but cannot be parsed is a real defect and gets one line on
    stderr.
    """
    for path in candidates:
        if not path.is_file():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            settings = data["platforms"]["claude"]["settings"]
            if not isinstance(settings, dict) or not settings:
                raise ValueError("platforms.claude.settings is empty or not an object")
        except (OSError, ValueError, KeyError, TypeError) as exc:
            print(
                f"note: {path} is unreadable ({exc}); using built-in Claude defaults.",
                file=sys.stderr,
            )
            break
        return copy.deepcopy(settings)
    return copy.deepcopy(_FALLBACK_SETTINGS)


def build_project_settings_stub(candidates=_DEFAULTS_CANDIDATES) -> dict:
    """Compose the `.claude/settings.json` stub that `nexus-hub init` writes.

    Composed at call time rather than at import time so the declared values are
    read from disk on every run, which is what makes editing
    configs/platform-defaults.json change what init writes with no code edit.
    """
    stub: dict = {"_comment": _STUB_COMMENT}
    stub.update(_load_declared_settings(candidates))
    stub["permissions"] = copy.deepcopy(_STUB_PERMISSIONS)
    return stub


class ClaudeIntegration(MarkdownIntegration, SkillsIntegration):
    key = "claude"
    display_name = "Claude Code (Anthropic)"
    instruction_mode = "shared"
    config = {
        "global_dir": "~/.claude",
        "workspace_dir": ".claude",
        # Workspace CLAUDE.md lands at the project root (where Claude Code reads
        # it), not under .claude/; skills/commands/agents/rules still mirror
        # under .claude/. Matches the legacy bash installer (DF-001).
        "instruction_workspace_dir": "",
        "instruction_file": "CLAUDE.md",
        "instruction_template": "templates/ai-instructions/base-claude.md",
        # Claude Code discovers skills one level deep (~/.claude/skills/<name>/
        # SKILL.md), so flatten the catalog's <category>/ layer and surface each
        # command as a skill too (v3.12.0 Phase 4).
        "skills_subdir": "skills",
        "flatten_skills_layout": True,
        "commands_subdir": "commands",
        "agents_subdir": "agents",
        "rules_subdir": "rules",
        "hooks_subdir": "hooks",
        "hooks_supported": True,
    }

    def wire_project_surfaces(self, ctx: InstallContext) -> WriteResult:
        """Write a `.claude/settings.json` stub when none exists.

        `nexus-hub init` calls this to bootstrap a Claude project surface from
        a global install. The stub never overwrites an existing settings.json;
        it returns `kept` so the user's customizations survive.
        """
        result = WriteResult()
        claude_dir = (ctx.target_root / self.config["workspace_dir"]).resolve()
        if not ctx.dry_run:
            claude_dir.mkdir(parents=True, exist_ok=True)
        dst = claude_dir / "settings.json"
        if dst.exists():
            ctx.manifest.log(self.key, f"skip-existing: {dst}")
            result.files.append(FileAction(path=str(dst), action="kept"))
            return result
        body = json.dumps(build_project_settings_stub(), indent=2) + "\n"
        if not ctx.dry_run:
            dst.write_text(body, encoding="utf-8")
        ctx.manifest.track(self.key, str(dst))
        result.files.append(FileAction(path=str(dst), action="created"))
        return result
