"""Kimi integration.

Kimi reads a small ``agent.yaml`` manifest that points at a ``system.md`` system
prompt. Nexus-Hub emits both into a ``.kimi/`` directory: ``system.md`` carries
the rendered Nexus-Hub instruction set (including the embedded
``{{SKILL_INDEX}}`` block) and ``agent.yaml`` is a stable manifest referencing
it. This is a behavioral-guardrails surface, not a slash-command surface.

Workspace scope writes ``<project>/.kimi/system.md`` (shared marker-merged so
user edits survive a re-install) plus ``<project>/.kimi/agent.yaml`` (a
deterministic, Nexus-Hub-owned companion). Global scope writes the same pair
under ``~/.kimi/`` when the Kimi config root (``~/.kimi``) is present, and skips
with a note otherwise (mirroring the Windsurf detection model).

MIGRATION NOTE (dated, 2026-07-08, v3.11.0 Phase 3): Kimi CLI was
rebuilt as "Kimi Code CLI" (a Python -> Node.js rewrite, v0.1.0 May 2026;
primary: https://www.kimi.com/code/docs/en/kimi-code-cli/guides/migration.html).
The migration is NON-destructive to this layout: the guide states "Migration
never modifies or deletes any of the old data under ``~/.kimi/``", so the
legacy ``~/.kimi/`` layout coexists with the new install and the surface this
integration writes is STILL SERVED. No primary source confirms the project-local
``.kimi/system.md`` + ``.kimi/agent.yaml`` layout is rejected by Kimi Code CLI,
so it is intentionally NOT rewritten here (``scripts/lib/integrations/`` is an
"ask first" surface and a speculative rewrite risks breaking existing installs).
A refresh to any Kimi-Code-CLI-specific project-local convention is deferred to
known-gaps pending maintainer confirmation. See
docs/v3/v3.11/development/roster-verification.md.
"""

from __future__ import annotations

from pathlib import Path

from .base import InstallContext, MarkdownIntegration
from .result import WriteResult

# Deterministic companion manifest. Kept constant (not templated) so the file is
# byte-identical across runs and projects, which keeps the install idempotent.
_AGENT_YAML = """\
# Nexus-Hub Kimi agent manifest.
# The system prompt lives in system.md (the rendered Nexus-Hub instruction set,
# including the skill index). Generated by the Nexus-Hub installer; safe to edit.
name: nexus-hub
system_prompt_file: system.md
"""


class KimiIntegration(MarkdownIntegration):
    key = "kimi"
    display_name = "Kimi"
    instruction_mode = "shared"
    config = {
        # Global pair lives under ~/.kimi, handled by install_global below
        # (gated on detection), so no simple home-relative global_dir.
        "global_dir": None,
        "instruction_workspace_dir": ".kimi",
        "instruction_file": "system.md",
        "instruction_template": "templates/ai-instructions/base-kimi.md",
        "hooks_supported": False,
    }

    def install_workspace(self, ctx: InstallContext) -> WriteResult:
        # super() renders <root>/.kimi/system.md via instruction_workspace_dir.
        result = super().install_workspace(ctx)
        kimi_dir = (ctx.target_root / self.config["instruction_workspace_dir"]).resolve()
        self._ensure_dir(kimi_dir, ctx)
        result.files.append(
            self._write_generated(kimi_dir / "agent.yaml", _AGENT_YAML, ctx, self.key)
        )
        return result

    def install_global(self, ctx: InstallContext) -> WriteResult:
        """Write ``~/.kimi/{system.md,agent.yaml}`` when Kimi is detected, else
        skip with a note.

        Detection: the Kimi config root ``~/.kimi`` must exist. When it does not,
        Kimi is not installed for this user and the global write is skipped (the
        workspace-scope ``.kimi/`` pair is the primary surface and is
        unaffected).
        """
        result = WriteResult()
        kimi_root = (Path.home() / ".kimi").resolve()
        if not kimi_root.exists():
            ctx.manifest.log(self.key, "~/.kimi not found; skipping global Kimi files")
            result.note("Kimi (~/.kimi) not found; global agent.yaml + system.md skipped")
            return result
        self._ensure_dir(kimi_root, ctx)
        action = self._write_instruction(kimi_root, ctx)
        if action is not None:
            result.files.append(action)
        result.files.append(
            self._write_generated(kimi_root / "agent.yaml", _AGENT_YAML, ctx, self.key)
        )
        return result
