"""Kimi integration.

Kimi Code CLI injects the MERGED ``AGENTS.md`` (concatenated from the project
root down to the working directory, INCLUDING ``.kimi/AGENTS.md``) as its
project context. Nexus-Hub emits ``.kimi/AGENTS.md`` carrying the rendered
Nexus-Hub instruction set (including the embedded ``{{SKILL_INDEX}}`` block),
plus an optional ``agent.yaml`` manifest (usable via ``kimi --agent-file``) that
references it. This is a behavioral-guardrails surface, not a slash-command
surface.

Workspace scope writes ``<project>/.kimi/AGENTS.md`` (shared marker-merged so
user edits survive a re-install) plus ``<project>/.kimi/agent.yaml`` (a
deterministic, Nexus-Hub-owned companion). Global scope writes the same pair
under ``~/.kimi/`` when the Kimi config root (``~/.kimi``) is present, and skips
with a note otherwise (mirroring the Windsurf detection model).

MIGRATION NOTE (RESOLVED, 2026-07-19, v3.14.5 release re-verification): the
earlier layout wrote ``.kimi/system.md`` + ``.kimi/agent.yaml`` on the belief
(v3.11.0) that it was "still served". Re-verification against the current Kimi
Code CLI docs (https://moonshotai.github.io/kimi-cli/) found that
``.kimi/system.md`` is NOT auto-discovered - it is a custom-agent-definition
file loaded only via the ``--agent-file`` flag - while the auto-injected project
context is the merged ``AGENTS.md`` (built-in ``${KIMI_AGENTS_MD}`` explicitly
includes ``.kimi/AGENTS.md``). So the old surface never reached Kimi. The
instruction file is now ``.kimi/AGENTS.md`` (in the read-merge). This resolves
the previously-deferred known-gap; the maintainer authorized the fix in the
v3.14.5 release flow. See docs/v3/v3.11/development/roster-verification.md.
"""

from __future__ import annotations

from pathlib import Path

from .base import InstallContext, MarkdownIntegration
from .result import WriteResult

# Deterministic companion manifest. Kept constant (not templated) so the file is
# byte-identical across runs and projects, which keeps the install idempotent.
_AGENT_YAML = """\
# Nexus-Hub Kimi agent manifest (optional; usable via `kimi --agent-file`).
# The system prompt lives in AGENTS.md (the rendered Nexus-Hub instruction set,
# including the skill index), which Kimi Code CLI also auto-includes in its
# merged project context. Generated by the Nexus-Hub installer; safe to edit.
name: nexus-hub
system_prompt_file: AGENTS.md
"""


class KimiIntegration(MarkdownIntegration):
    key = "kimi"
    display_name = "Kimi"
    instruction_mode = "shared"
    config = {
        # Global pair lives under ~/.kimi, handled by install_global below
        # (gated on detection), so no simple home-relative global_dir.
        "global_dir": None,
        "instruction_workspace_dir": ".kimi",
        # v3.14.5: Kimi Code CLI injects the MERGED AGENTS.md (project root ->
        # cwd, INCLUDING .kimi/AGENTS.md) as its project context; the old
        # .kimi/system.md was NOT auto-discovered (it is a custom-agent-definition
        # file loaded only via --agent-file), so our instruction never reached
        # Kimi. Write .kimi/AGENTS.md so it lands in Kimi's read-merge. Re-verified
        # 2026-07-19 against https://moonshotai.github.io/kimi-cli/ docs.
        "instruction_file": "AGENTS.md",
        "instruction_template": "templates/ai-instructions/base-kimi.md",
        "hooks_supported": False,
    }

    def install_workspace(self, ctx: InstallContext) -> WriteResult:
        # super() renders <root>/.kimi/system.md via instruction_workspace_dir.
        result = super().install_workspace(ctx)
        kimi_dir = (ctx.target_root / self.config["instruction_workspace_dir"]).resolve()
        self._ensure_dir(kimi_dir, ctx)
        result.files.append(
            self._write_generated(kimi_dir / "agent.yaml", _AGENT_YAML, ctx, self.key)
        )
        return result

    def install_global(self, ctx: InstallContext) -> WriteResult:
        """Write ``~/.kimi/{system.md,agent.yaml}`` when Kimi is detected, else
        skip with a note.

        Detection: the Kimi config root ``~/.kimi`` must exist. When it does not,
        Kimi is not installed for this user and the global write is skipped (the
        workspace-scope ``.kimi/`` pair is the primary surface and is
        unaffected).
        """
        result = WriteResult()
        kimi_root = (Path.home() / ".kimi").resolve()
        if not kimi_root.exists():
            ctx.manifest.log(self.key, "~/.kimi not found; skipping global Kimi files")
            result.mark_not_detected("Kimi (~/.kimi) not found; global agent.yaml + system.md skipped")
            return result
        result.detected = True
        self._ensure_dir(kimi_root, ctx)
        action = self._write_instruction(kimi_root, ctx)
        if action is not None:
            result.files.append(action)
        result.files.append(
            self._write_generated(kimi_root / "agent.yaml", _AGENT_YAML, ctx, self.key)
        )
        return result
