"""OpenClaw integration.

OpenClaw treats each configured agent workspace as the primary customization
root. It reads ``AGENTS.md``, ``SOUL.md``, and ``IDENTITY.md`` from that root and
discovers folder-per-skill ``SKILL.md`` files one level below ``skills/``.
Nexus-Hub therefore marker-merges the instruction file at the workspace root,
writes the two stable companions beside it, and flattens catalog skills plus
command-skills into the native ``skills`` directory.

Global scope resolves OpenClaw's active config and state paths through the
documented ``OPENCLAW_CONFIG_PATH``, ``OPENCLAW_STATE_DIR``, and
``OPENCLAW_HOME`` overrides. The workspace then resolves from
``agents.defaults.workspace`` in the active config, ``OPENCLAW_WORKSPACE_DIR``,
or ``<stateDir>/workspace``, in that order. Workspace scope treats the requested
target as the configured workspace itself; it does not invent a project-local
``.openclaw`` subdirectory that OpenClaw would not scan as a workspace root.

OpenClaw also has native internal lifecycle hooks under ``<stateDir>/hooks`` and
``<workspace>/hooks``. Those handlers observe command, session, message, agent,
and gateway events but cannot intercept tools or cancel operations. Tool-gating
parity requires an explicitly installed typed plugin using ``api.on(...)``.
Nexus-Hub does not fabricate a shell-hook mapping or silently install such a
plugin, so catalog guardrail-hook delivery remains NOT COVERED for OpenClaw.
"""

from __future__ import annotations

import ast
import json
import os
from pathlib import Path
from typing import Any, ClassVar

from .base import InstallContext, MarkdownIntegration, SkillsIntegration
from .result import WriteResult

# Deterministic companion files. Kept constant (not templated) so they are
# byte-identical across runs and projects, which keeps the install idempotent.
_SOUL_MD = """\
# SOUL

This workspace follows the Nexus-Hub conventions. The operative behavioral
guidance, working conventions, and full skill index live in `AGENTS.md` beside
this file. Read `AGENTS.md` first.

Generated by the Nexus-Hub installer; safe to extend below this line.
"""

_IDENTITY_MD = """\
# IDENTITY

Agent identity for this workspace is grounded in the Nexus-Hub instruction set
in `AGENTS.md` (see the skill index and working conventions there). This file is
a stable placeholder for workspace-specific identity notes.

Generated by the Nexus-Hub installer; safe to extend below this line.
"""


class OpenClawConfigError(ValueError):
    """Raised when the selected OpenClaw config cannot be used safely."""


_MAX_INCLUDE_DEPTH = 10
_MAX_INCLUDE_PATH_CHARS = 4096
_MAX_ROOT_CONFIG_BYTES = 4 * 1024 * 1024
_MAX_INCLUDE_FILE_BYTES = 2 * 1024 * 1024
_MAX_CONFIG_TOTAL_BYTES = 16 * 1024 * 1024


def _strip_json5_comments(text: str) -> str:
    """Remove JSON5 line/block comments while preserving quoted strings."""
    out: list[str] = []
    index = 0
    quote: str | None = None
    escaped = False
    while index < len(text):
        char = text[index]
        nxt = text[index + 1] if index + 1 < len(text) else ""
        if quote is not None:
            out.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            index += 1
            continue
        if char in {'"', "'"}:
            quote = char
            out.append(char)
            index += 1
            continue
        if char == "/" and nxt == "/":
            index += 2
            while index < len(text) and text[index] not in "\r\n":
                index += 1
            continue
        if char == "/" and nxt == "*":
            index += 2
            while index + 1 < len(text) and text[index : index + 2] != "*/":
                index += 1
            if index + 1 >= len(text):
                raise OpenClawConfigError("unterminated block comment")
            index += 2
            continue
        out.append(char)
        index += 1
    return "".join(out)


def _normalize_json5_strings(text: str) -> str:
    """Convert JSON5 single-quoted strings to JSON strings.

    OpenClaw's documented examples use ordinary JSON5 strings and do not need a
    general JavaScript evaluator. ``ast.literal_eval`` handles the escape rules
    for a single isolated string without executing code; all other tokens remain
    for ``json.loads`` to validate.
    """
    out: list[str] = []
    index = 0
    while index < len(text):
        char = text[index]
        if char not in {'"', "'"}:
            out.append(char)
            index += 1
            continue

        quote = char
        start = index
        index += 1
        escaped = False
        while index < len(text):
            current = text[index]
            index += 1
            if escaped:
                escaped = False
            elif current == "\\":
                escaped = True
            elif current == quote:
                break
        else:
            raise OpenClawConfigError("unterminated string")

        token = text[start:index]
        if quote == '"':
            out.append(token)
            continue
        try:
            value = ast.literal_eval(token)
        except (SyntaxError, ValueError) as exc:
            raise OpenClawConfigError("invalid single-quoted string") from exc
        if not isinstance(value, str):
            raise OpenClawConfigError("single-quoted token is not a string")
        out.append(json.dumps(value, ensure_ascii=False))
    return "".join(out)


def _quote_json5_keys(text: str) -> str:
    """Quote unquoted JSON5 identifier keys without touching string content."""
    out: list[str] = []
    index = 0
    previous_significant = ""
    while index < len(text):
        char = text[index]
        if char == '"':
            start = index
            index += 1
            escaped = False
            while index < len(text):
                current = text[index]
                index += 1
                if escaped:
                    escaped = False
                elif current == "\\":
                    escaped = True
                elif current == '"':
                    break
            out.append(text[start:index])
            previous_significant = '"'
            continue
        if (
            previous_significant in {"{", ","}
            and (char.isalpha() or char in {"_", "$"})
        ):
            end = index + 1
            while end < len(text) and (
                text[end].isalnum() or text[end] in {"_", "$"}
            ):
                end += 1
            colon = end
            while colon < len(text) and text[colon].isspace():
                colon += 1
            if colon < len(text) and text[colon] == ":":
                out.append(json.dumps(text[index:end], ensure_ascii=False))
                previous_significant = '"'
                index = end
                continue
        out.append(char)
        if not char.isspace():
            previous_significant = char
        index += 1
    return "".join(out)


def _remove_json5_trailing_commas(text: str) -> str:
    """Remove object/array trailing commas without matching inside strings."""
    out: list[str] = []
    index = 0
    while index < len(text):
        char = text[index]
        if char == '"':
            start = index
            index += 1
            escaped = False
            while index < len(text):
                current = text[index]
                index += 1
                if escaped:
                    escaped = False
                elif current == "\\":
                    escaped = True
                elif current == '"':
                    break
            out.append(text[start:index])
            continue
        if char == ",":
            lookahead = index + 1
            while lookahead < len(text) and text[lookahead].isspace():
                lookahead += 1
            if lookahead < len(text) and text[lookahead] in {"}", "]"}:
                index += 1
                continue
        out.append(char)
        index += 1
    return "".join(out)


def _parse_openclaw_json5(
    path: Path, byte_budget: list[int], *, max_file_bytes: int
) -> dict[str, Any]:
    """Read one bounded OpenClaw JSON5 object without resolving includes."""
    try:
        file_size = path.stat().st_size
        if file_size > max_file_bytes:
            raise OpenClawConfigError(f"config file exceeds size limit: {path}")
        raw_bytes = path.read_bytes()
    except OpenClawConfigError:
        raise
    except OSError as exc:
        raise OpenClawConfigError(f"cannot read selected config: {path}") from exc
    if len(raw_bytes) > max_file_bytes:
        raise OpenClawConfigError(f"config file exceeds size limit: {path}")
    if byte_budget[0] + len(raw_bytes) > _MAX_CONFIG_TOTAL_BYTES:
        raise OpenClawConfigError("config include graph exceeds total size limit")
    byte_budget[0] += len(raw_bytes)
    try:
        raw = raw_bytes.decode("utf-8")
    except UnicodeError as exc:
        raise OpenClawConfigError(f"cannot decode selected config: {path}") from exc
    try:
        normalized = _strip_json5_comments(raw)
        normalized = _normalize_json5_strings(normalized)
        normalized = _quote_json5_keys(normalized)
        normalized = _remove_json5_trailing_commas(normalized)
        payload = json.loads(normalized)
    except json.JSONDecodeError as exc:
        raise OpenClawConfigError(
            f"invalid JSON5 at line {exc.lineno}, column {exc.colno}: {path}"
        ) from exc
    if not isinstance(payload, dict):
        raise OpenClawConfigError(f"config root must be an object: {path}")
    return payload


def _is_network_or_device_path(value: str) -> bool:
    normalized = value.replace("/", "\\")
    return normalized.startswith("\\\\")


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _include_roots(config_path: Path) -> tuple[Path, ...]:
    """Return canonical roots permitted by OpenClaw's include contract."""
    try:
        config_root = config_path.parent.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise OpenClawConfigError(
            f"cannot resolve selected config directory: {config_path.parent}"
        ) from exc
    if _is_network_or_device_path(str(config_root)):
        raise OpenClawConfigError("network config paths are not supported")

    roots = [config_root]
    configured_roots = os.environ.get("OPENCLAW_INCLUDE_ROOTS", "")
    for item in configured_roots.split(os.pathsep):
        value = item.strip()
        if not value:
            continue
        if "\0" in value or len(value) >= _MAX_INCLUDE_PATH_CHARS:
            raise OpenClawConfigError("invalid OPENCLAW_INCLUDE_ROOTS path")
        if "://" in value or _is_network_or_device_path(value):
            raise OpenClawConfigError("network include roots are not supported")
        candidate = Path(value).expanduser()
        if not candidate.is_absolute():
            raise OpenClawConfigError(
                "OPENCLAW_INCLUDE_ROOTS entries must be absolute paths"
            )
        try:
            root = candidate.resolve(strict=True)
        except (OSError, RuntimeError) as exc:
            raise OpenClawConfigError(
                f"cannot resolve OPENCLAW_INCLUDE_ROOTS entry: {value}"
            ) from exc
        if not root.is_dir() or _is_network_or_device_path(str(root)):
            raise OpenClawConfigError(
                f"OPENCLAW_INCLUDE_ROOTS entry is not a local directory: {value}"
            )
        roots.append(root)
    return tuple(roots)


def _resolve_include_path(
    value: str, including_path: Path, allowed_roots: tuple[Path, ...]
) -> Path:
    if not value or not value.strip():
        raise OpenClawConfigError("$include path must be a non-empty string")
    if "\0" in value or len(value) >= _MAX_INCLUDE_PATH_CHARS:
        raise OpenClawConfigError("$include path is invalid or too long")
    if "://" in value or _is_network_or_device_path(value):
        raise OpenClawConfigError("network $include paths are not supported")

    candidate = Path(value)
    if not candidate.is_absolute():
        candidate = including_path.parent / candidate
    try:
        resolved = candidate.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise OpenClawConfigError(f"included config does not exist: {value}") from exc
    if len(str(resolved)) >= _MAX_INCLUDE_PATH_CHARS:
        raise OpenClawConfigError("resolved $include path is too long")
    if _is_network_or_device_path(str(resolved)):
        raise OpenClawConfigError("network $include paths are not supported")
    if not any(_is_within(resolved, root) for root in allowed_roots):
        raise OpenClawConfigError(
            f"included config escapes the permitted config roots: {value}"
        )
    if not resolved.is_file():
        raise OpenClawConfigError(f"included config is not a file: {value}")
    return resolved


def _deep_merge(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    """Deep-merge objects, with later values replacing earlier values."""
    merged = dict(left)
    for key, right_value in right.items():
        left_value = merged.get(key)
        if isinstance(left_value, dict) and isinstance(right_value, dict):
            merged[key] = _deep_merge(left_value, right_value)
        else:
            merged[key] = right_value
    return merged


def _resolve_config_value(
    value: Any,
    including_path: Path,
    allowed_roots: tuple[Path, ...],
    stack: tuple[Path, ...],
    depth: int,
    byte_budget: list[int],
) -> Any:
    if isinstance(value, list):
        return [
            _resolve_config_value(
                item, including_path, allowed_roots, stack, depth, byte_budget
            )
            for item in value
        ]
    if not isinstance(value, dict):
        return value

    include_value = value.get("$include")
    if "$include" not in value:
        return {
            key: _resolve_config_value(
                item, including_path, allowed_roots, stack, depth, byte_budget
            )
            for key, item in value.items()
        }

    if isinstance(include_value, str):
        include_paths = [include_value]
    elif isinstance(include_value, list) and include_value:
        if not all(isinstance(item, str) for item in include_value):
            raise OpenClawConfigError("$include array entries must be strings")
        include_paths = include_value
    else:
        raise OpenClawConfigError("$include must be a string or non-empty array")

    merged: dict[str, Any] = {}
    for include_path in include_paths:
        resolved = _resolve_include_path(include_path, including_path, allowed_roots)
        included = _load_openclaw_config(
            resolved,
            allowed_roots=allowed_roots,
            stack=stack,
            depth=depth + 1,
            byte_budget=byte_budget,
        )
        merged = _deep_merge(merged, included)

    siblings = {
        key: _resolve_config_value(
            item, including_path, allowed_roots, stack, depth, byte_budget
        )
        for key, item in value.items()
        if key != "$include"
    }
    return _deep_merge(merged, siblings)


def _load_openclaw_config(
    path: Path,
    *,
    allowed_roots: tuple[Path, ...],
    stack: tuple[Path, ...],
    depth: int,
    byte_budget: list[int],
) -> dict[str, Any]:
    if depth > _MAX_INCLUDE_DEPTH:
        raise OpenClawConfigError(
            f"$include depth exceeds {_MAX_INCLUDE_DEPTH} levels"
        )
    try:
        canonical_path = path.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise OpenClawConfigError(f"selected config does not exist: {path}") from exc
    if canonical_path in stack:
        raise OpenClawConfigError(f"$include cycle detected at: {canonical_path}")
    if not any(_is_within(canonical_path, root) for root in allowed_roots):
        raise OpenClawConfigError(
            f"config escapes the permitted config roots: {canonical_path}"
        )
    max_file_bytes = (
        _MAX_ROOT_CONFIG_BYTES if depth == 0 else _MAX_INCLUDE_FILE_BYTES
    )
    payload = _parse_openclaw_json5(
        canonical_path, byte_budget, max_file_bytes=max_file_bytes
    )
    resolved = _resolve_config_value(
        payload,
        canonical_path,
        allowed_roots,
        (*stack, canonical_path),
        depth,
        byte_budget,
    )
    if not isinstance(resolved, dict):
        raise OpenClawConfigError(f"config root must be an object: {canonical_path}")
    return resolved


def _read_openclaw_config(
    path: Path, *, required: bool = False
) -> dict[str, Any]:
    """Read a bounded OpenClaw JSON5 include graph or raise on unsafe config."""
    if not path.exists():
        if required:
            raise OpenClawConfigError(f"selected config does not exist: {path}")
        return {}
    try:
        canonical_path = path.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise OpenClawConfigError(f"cannot resolve selected config: {path}") from exc
    allowed_roots = _include_roots(canonical_path)
    return _load_openclaw_config(
        canonical_path,
        allowed_roots=allowed_roots,
        stack=(),
        depth=0,
        byte_budget=[0],
    )


def _resolve_workspace_path(value: str, home: Path) -> Path:
    expanded = os.path.expandvars(value.strip())
    if expanded == "~":
        candidate = home
    elif expanded.startswith(("~/", "~\\")):
        candidate = home / expanded[2:]
    else:
        candidate = Path(expanded)
    if not candidate.is_absolute():
        candidate = home / candidate
    return candidate.resolve()


def _openclaw_locations(openclaw_root: Path) -> tuple[Path, Path, Path, bool]:
    """Resolve effective home, state, and config paths from official overrides."""
    system_home = openclaw_root.resolve().parent
    configured_home = os.environ.get("OPENCLAW_HOME", "").strip()
    effective_home = (
        _resolve_workspace_path(configured_home, system_home)
        if configured_home
        else system_home
    )

    configured_state = os.environ.get("OPENCLAW_STATE_DIR", "").strip()
    if configured_state:
        state_dir = _resolve_workspace_path(configured_state, effective_home)
    elif configured_home:
        state_dir = (effective_home / ".openclaw").resolve()
    else:
        state_dir = openclaw_root.resolve()

    configured_path = os.environ.get("OPENCLAW_CONFIG_PATH", "").strip()
    config_path = (
        _resolve_workspace_path(configured_path, effective_home)
        if configured_path
        else (state_dir / "openclaw.json").resolve()
    )
    return effective_home, state_dir, config_path, bool(configured_path)


def _openclaw_is_active(openclaw_root: Path) -> bool:
    """Return whether default state or an explicit OpenClaw target is active."""
    if any(
        os.environ.get(name, "").strip()
        for name in (
            "OPENCLAW_HOME",
            "OPENCLAW_STATE_DIR",
            "OPENCLAW_CONFIG_PATH",
            "OPENCLAW_WORKSPACE_DIR",
        )
    ):
        return True
    _, state_dir, config_path, _ = _openclaw_locations(openclaw_root)
    return state_dir.is_dir() or config_path.exists()


def _configured_workspace(openclaw_root: Path) -> Path:
    """Resolve OpenClaw's configured default workspace without modifying config."""
    home, state_dir, config_path, config_required = _openclaw_locations(openclaw_root)
    config = _read_openclaw_config(config_path, required=config_required)

    agents: dict[str, Any] = {}
    if "agents" in config:
        if not isinstance(config["agents"], dict):
            raise OpenClawConfigError("config agents value must be an object")
        agents = config["agents"]

    defaults: dict[str, Any] = {}
    if "defaults" in agents:
        if not isinstance(agents["defaults"], dict):
            raise OpenClawConfigError("config agents.defaults value must be an object")
        defaults = agents["defaults"]

    if "workspace" in defaults:
        configured = defaults["workspace"]
        if not isinstance(configured, str) or not configured.strip():
            raise OpenClawConfigError(
                "config agents.defaults.workspace must be a non-empty string"
            )
        return _resolve_workspace_path(configured, home)

    from_env = os.environ.get("OPENCLAW_WORKSPACE_DIR", "").strip()
    if from_env:
        return _resolve_workspace_path(from_env, home)
    return (state_dir / "workspace").resolve()


class OpenClawIntegration(MarkdownIntegration, SkillsIntegration):
    key = "openclaw"
    display_name = "OpenClaw"
    instruction_mode = "shared"
    config: ClassVar[dict[str, Any]] = {
        # Global delivery resolves the configured workspace in install_global.
        "global_dir": None,
        # A workspace target is already the OpenClaw workspace root.
        "workspace_dir": "",
        "instruction_workspace_dir": "",
        "instruction_file": "AGENTS.md",
        "instruction_template": "templates/ai-instructions/base-openclaw.md",
        "skills_subdir": "skills",
        "flatten_skills_layout": True,
        # Internal hooks cannot gate tools; typed-plugin development is outside
        # this adapter and catalog guardrail parity remains NOT COVERED.
        "hooks_supported": False,
    }

    def _write_workspace(self, workspace: Path, ctx: InstallContext) -> WriteResult:
        result = WriteResult()
        self._ensure_dir(workspace, ctx)
        action = self._write_instruction(workspace, ctx)
        if action is not None:
            result.files.append(action)
        result.files.extend(
            [
                self._write_generated(workspace / "SOUL.md", _SOUL_MD, ctx, self.key),
                self._write_generated(
                    workspace / "IDENTITY.md", _IDENTITY_MD, ctx, self.key
                ),
            ]
        )
        if not ctx.instruction_only:
            result.files.extend(self._mirror_catalog(workspace, ctx))
            result.note(
                "OpenClaw lifecycle hooks are native, but Nexus-Hub tool-interception "
                "guardrails require a typed plugin and were not installed."
            )
        return result

    def install_workspace(self, ctx: InstallContext) -> WriteResult:
        """Install at the requested OpenClaw workspace root."""
        return self._write_workspace(ctx.target_root.resolve(), ctx)

    def install_global(self, ctx: InstallContext) -> WriteResult:
        """Install into the configured default workspace when OpenClaw is detected."""
        openclaw_root = (Path.home() / ".openclaw").resolve()
        try:
            _, state_dir, config_path, _config_required = _openclaw_locations(
                openclaw_root
            )
        except (OSError, ValueError) as exc:
            result = WriteResult()
            message = (
                f"OpenClaw path configuration is unusable: {exc}; "
                "global workspace surfaces skipped"
            )
            ctx.manifest.log(self.key, message)
            result.mark_not_detected(message)
            return result
        if not _openclaw_is_active(openclaw_root):
            result = WriteResult()
            ctx.manifest.log(
                self.key,
                f"OpenClaw state directory not found at {state_dir}; skipping global files",
            )
            result.mark_not_detected(
                f"OpenClaw state directory ({state_dir}) not found; "
                "global workspace surfaces skipped"
            )
            return result
        try:
            workspace = _configured_workspace(openclaw_root)
        except (OSError, ValueError) as exc:
            result = WriteResult()
            message = (
                f"OpenClaw config ({config_path}) is unusable: {exc}; "
                "global workspace surfaces skipped"
            )
            ctx.manifest.log(self.key, message)
            result.mark_not_detected(message)
            return result
        result = self._write_workspace(workspace, ctx)
        result.detected = True
        return result


__all__ = [
    "OpenClawConfigError",
    "OpenClawIntegration",
    "_configured_workspace",
    "_openclaw_is_active",
    "_read_openclaw_config",
]
