"""OpenClaw integration.

OpenClaw splits agent guidance across three files: ``SOUL.md``, ``AGENTS.md``,
and ``IDENTITY.md``. Nexus-Hub emits all three into an ``.openclaw/`` directory
(namespaced so the project-root ``AGENTS.md`` other integrations write is not
touched). ``AGENTS.md`` carries the rendered Nexus-Hub instruction set
(including the embedded ``{{SKILL_INDEX}}`` block); ``SOUL.md`` and
``IDENTITY.md`` are stable companions that point at it. This is a
behavioral-guardrails surface, not a slash-command surface.

Workspace scope writes ``<project>/.openclaw/AGENTS.md`` (shared marker-merged
so user edits survive a re-install) plus the two deterministic companions.
Global scope writes the same trio under ``~/.openclaw/`` when the OpenClaw
config root (``~/.openclaw``) is present, and skips with a note otherwise
(mirroring the Windsurf detection model).
"""

from __future__ import annotations

from pathlib import Path

from .base import InstallContext, MarkdownIntegration
from .result import WriteResult

# Deterministic companion files. Kept constant (not templated) so they are
# byte-identical across runs and projects, which keeps the install idempotent.
_SOUL_MD = """\
# SOUL

This project follows the Nexus-Hub conventions. The operative behavioral
guidance, working conventions, and the full skill index live in `AGENTS.md`
alongside this file. Read `AGENTS.md` first.

Generated by the Nexus-Hub installer; safe to extend below this line.
"""

_IDENTITY_MD = """\
# IDENTITY

Agent identity for this workspace is grounded in the Nexus-Hub instruction set
in `AGENTS.md` (see the skill index and working conventions there). This file is
a stable placeholder for workspace-specific identity notes.

Generated by the Nexus-Hub installer; safe to extend below this line.
"""


class OpenClawIntegration(MarkdownIntegration):
    key = "openclaw"
    display_name = "OpenClaw"
    instruction_mode = "shared"
    config = {
        # Global trio lives under ~/.openclaw, handled by install_global below
        # (gated on detection), so no simple home-relative global_dir.
        "global_dir": None,
        "instruction_workspace_dir": ".openclaw",
        "instruction_file": "AGENTS.md",
        "instruction_template": "templates/ai-instructions/base-openclaw.md",
        # No autonomy descriptor: no-prompt exec requires config plus host-local approval state; see the platform read-contract autonomy section.
        "hooks_supported": False,
    }

    def _write_companions(self, parent: Path, ctx: InstallContext) -> list:
        """Write SOUL.md + IDENTITY.md under ``parent``; return their actions."""
        return [
            self._write_generated(parent / "SOUL.md", _SOUL_MD, ctx, self.key),
            self._write_generated(parent / "IDENTITY.md", _IDENTITY_MD, ctx, self.key),
        ]

    def install_workspace(self, ctx: InstallContext) -> WriteResult:
        # super() renders <root>/.openclaw/AGENTS.md via instruction_workspace_dir.
        result = super().install_workspace(ctx)
        oc_dir = (ctx.target_root / self.config["instruction_workspace_dir"]).resolve()
        self._ensure_dir(oc_dir, ctx)
        result.files.extend(self._write_companions(oc_dir, ctx))
        return result

    def install_global(self, ctx: InstallContext) -> WriteResult:
        """Write ``~/.openclaw/workspace/{SOUL,AGENTS,IDENTITY}.md`` when OpenClaw
        is detected, else skip with a note.

        v3.14.5: OpenClaw reads its agent files from the single global workspace
        directory ``~/.openclaw/workspace/`` (per-machine/profile), NOT from the
        config root ``~/.openclaw/`` directly - so the trio now lands under
        ``workspace/``. Re-verified 2026-07-19 against
        https://docs.openclaw.ai/concepts/agent-workspace (overridable via
        ``OPENCLAW_WORKSPACE_DIR`` / ``agents.defaults.workspace``).

        Detection: the OpenClaw config root ``~/.openclaw`` must exist. When it
        does not, OpenClaw is not installed for this user and the global write is
        skipped.
        """
        result = WriteResult()
        oc_root = (Path.home() / ".openclaw").resolve()
        if not oc_root.exists():
            ctx.manifest.log(self.key, "~/.openclaw not found; skipping global OpenClaw files")
            result.mark_not_detected("OpenClaw (~/.openclaw) not found; global SOUL/AGENTS/IDENTITY skipped")
            return result
        result.detected = True
        oc_workspace = (oc_root / "workspace").resolve()
        self._ensure_dir(oc_workspace, ctx)
        action = self._write_instruction(oc_workspace, ctx)
        if action is not None:
            result.files.append(action)
        result.files.extend(self._write_companions(oc_workspace, ctx))
        return result
