#!/usr/bin/env python3
"""Generate a SHA-256 supply-chain manifest for the distributed catalog tree.

At release time this computes a SHA-256 over every file in the distributed
catalog tree and writes ``MANIFEST.sha256`` at the repo root, in the standard
``<sha256><space><space><relative-path>`` text format that ``sha256sum -c``
understands. The manifest is committed with the release and rides inside the
install tarball, so a user who later runs ``nexus-hub verify`` can prove their
on-disk install matches the published catalog (see ``verify_install.py``).

Trust-model note: this manifest is a *content-integrity* record, not a
signature. It detects post-install on-disk tampering relative to the published
catalog; it is trustworthy to the extent the manifest itself came from the
signed release tag the install bootstrap already trusts. It is NOT a substitute
for verifying the download channel.

Manifest scope (documented and stable):

* Covers the distributed catalog subtrees: ``catalog/`` (skills, commands,
  agents, hooks, rules, style-guides, ...), ``templates/`` (documentation
  templates AND the ``ai-instructions/base-*.md`` instruction templates),
  ``scripts/`` (the installer + the tools the installer copies, plus the
  integration registry under ``scripts/lib/``), and ``data/`` (the generated
  catalog metadata the installer distributes).
* Excludes VCS, caches, build output, virtual-envs, and per-user / generated
  files (see ``_EXCLUDED_DIRS`` / ``_EXCLUDED_FILE_NAMES`` /
  ``_EXCLUDED_FILE_SUFFIXES``). The manifest file itself is never listed.
* The ``extensions/`` MCP-server sources are intentionally out of the initial
  manifest scope (they are pip-installed into a venv at install time); this is a
  documented boundary recorded in the v3.10.0 known-gaps, not an oversight.

This tool is strictly local: stdlib ``hashlib`` only (reused from
``scripts/lib/integrations/manifest.py``), no network access, no credential, and
no third-party dependency. Output ordering is sorted by path so the manifest is
byte-stable across runs on the same tree (cross-OS byte-equality is not
guaranteed because git autocrlf can change line endings on checkout).

Usage:
    python scripts/generate_manifest.py            # write <repo>/MANIFEST.sha256
    python scripts/generate_manifest.py --root DIR --output FILE
    python scripts/generate_manifest.py --print     # write to stdout, not a file

Exit codes:
    0  the manifest was written (or printed) successfully
    2  the root directory does not exist
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, Iterator, List, Tuple

# --- reuse the existing manifest hashing (no new hashing code) -------------
# Two import layouts are supported: the in-repo tree (scripts/lib/...) and the
# installed tree (~/.nexus-hub/scripts/lib/...). Both put this file's parent
# (the scripts dir) and the repo root on sys.path, then try each module path.
# This mirrors the shim in scripts/import_skills.py exactly.
_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
for _p in (str(_REPO_ROOT), str(_SCRIPTS_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

try:  # in-repo layout
    from scripts.lib.integrations.manifest import _hash_path
except ModuleNotFoundError:  # pragma: no cover - installed layout
    from lib.integrations.manifest import _hash_path  # type: ignore[no-redef]


# --- manifest scope (the single source of truth, imported by verify_install) -

# Top-level subtrees the installer distributes. The verifier walks exactly these
# roots so an unexpected file outside them is simply ignored, not flagged EXTRA.
COVERED_ROOTS: Tuple[str, ...] = ("catalog", "templates", "scripts", "data")

# Directory names pruned anywhere in the walk (VCS, caches, build, venvs).
_EXCLUDED_DIRS = frozenset(
    {
        ".git",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        "node_modules",
        ".venv",
        "venv",
        "dist",
        "build",
    }
)

# Exact filenames never listed (the manifest itself, OS cruft).
_EXCLUDED_FILE_NAMES = frozenset({"MANIFEST.sha256", ".DS_Store", "Thumbs.db"})

# Filename suffixes never listed (compiled / generated bytecode and egg metadata).
_EXCLUDED_FILE_SUFFIXES: Tuple[str, ...] = (".pyc", ".pyo", ".egg-info")

# The manifest line format: "<sha256><space><space><relative-posix-path>\n".
# Two spaces is sha256sum text mode, so `sha256sum -c MANIFEST.sha256` works.
_LINE_SEP = "  "


def _is_excluded_dir(name: str) -> bool:
    return name in _EXCLUDED_DIRS or name.endswith(".egg-info")


def _is_excluded_file(name: str) -> bool:
    if name in _EXCLUDED_FILE_NAMES:
        return True
    return any(name.endswith(suffix) for suffix in _EXCLUDED_FILE_SUFFIXES)


def iter_catalog_files(root: Path) -> Iterator[Path]:
    """Yield every covered, non-excluded regular file under ``root``.

    Walks only the ``COVERED_ROOTS`` subtrees of ``root`` (so files outside them
    are neither hashed nor flagged), pruning excluded directories in place and
    skipping excluded filenames. Yields absolute paths; ordering is not
    guaranteed here (callers that need determinism sort the resulting entries).
    """
    for top in COVERED_ROOTS:
        base = root / top
        if not base.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            # Prune excluded dirs in place so os.walk does not descend into them.
            dirnames[:] = sorted(d for d in dirnames if not _is_excluded_dir(d))
            for filename in sorted(filenames):
                if _is_excluded_file(filename):
                    continue
                yield Path(dirpath) / filename


def _relpath_posix(path: Path, root: Path) -> str:
    """Return ``path`` relative to ``root`` using forward slashes on every OS."""
    return path.relative_to(root).as_posix()


def compute_manifest(root: Path) -> List[Tuple[str, str]]:
    """Return a sorted list of ``(relative-posix-path, sha256-hex)`` entries.

    Files that cannot be hashed (unreadable, vanished mid-walk) are skipped.
    The list is sorted by path so the serialized manifest is byte-stable.
    """
    entries: List[Tuple[str, str]] = []
    for file_path in iter_catalog_files(root):
        digest = _hash_path(file_path)
        if digest is None:
            continue
        entries.append((_relpath_posix(file_path, root), digest))
    entries.sort(key=lambda entry: entry[0])
    return entries


def format_manifest(entries: List[Tuple[str, str]]) -> str:
    """Serialize ``(path, hash)`` entries to sha256sum text format with LF lines."""
    return "".join(f"{digest}{_LINE_SEP}{path}\n" for path, digest in entries)


def parse_manifest(text: str) -> Dict[str, str]:
    """Parse manifest text into a ``{relative-posix-path: sha256-hex}`` mapping.

    Tolerant of blank lines and either ``sha256sum`` mode marker (``  path`` for
    text, `` *path`` for binary). The path is everything after the first
    separator run, so paths containing spaces are preserved.
    """
    mapping: Dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.rstrip("\n").rstrip("\r")
        if not line.strip():
            continue
        # Split on the first 2-char separator ("  " text mode or " *" binary).
        digest = line[:64].strip()
        remainder = line[64:]
        if remainder.startswith(_LINE_SEP):
            path = remainder[len(_LINE_SEP):]
        elif remainder.startswith(" *"):
            path = remainder[2:]
        else:
            path = remainder.strip()
        path = path.strip()
        if digest and path:
            mapping[path] = digest
    return mapping


def write_manifest(root: Path, out_path: Path) -> int:
    """Compute and write the manifest for ``root`` to ``out_path``.

    Writes UTF-8 bytes with explicit LF line endings (so the file is identical
    regardless of the writing OS's default newline). Returns the entry count.
    """
    entries = compute_manifest(root)
    out_path.write_bytes(format_manifest(entries).encode("utf-8"))
    return len(entries)


def _eprint(message: str) -> None:
    print(message, file=sys.stderr)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="generate_manifest",
        description="Write a SHA-256 supply-chain manifest for the catalog tree.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=_REPO_ROOT,
        help="Repo root to hash (default: the repo this script lives in).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Manifest output path (default: <root>/MANIFEST.sha256).",
    )
    parser.add_argument(
        "--print",
        dest="to_stdout",
        action="store_true",
        help="Print the manifest to stdout instead of writing a file.",
    )
    return parser


def main(argv: List[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root: Path = args.root.resolve()
    if not root.is_dir():
        _eprint(f"generate_manifest: root directory not found: {root}")
        return 2

    if args.to_stdout:
        entries = compute_manifest(root)
        sys.stdout.write(format_manifest(entries))
        _eprint(f"generate_manifest: {len(entries)} files (stdout)")
        return 0

    out_path: Path = (args.output or (root / "MANIFEST.sha256")).resolve()
    count = write_manifest(root, out_path)
    _eprint(f"generate_manifest: wrote {count} entries to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
